version: '3'
services:
  coaches_postgres:
    image: 'postgres:latest'
    container_name: 'pg'
    environment:
      - 'POSTGRES_DB=coaches'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0000'
    ports:
      - "5432:5432"

    networks:
      - backend

  app:
    build: /.
    container_name: 'coaches_service'
    ports:
      - "8080:8080"
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/coaches'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=0000'
    depends_on:
      - coaches_postgres
    networks:
      - backend

networks:
  backend:

volumes:
  pg-data: