version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'coaches_postgres'
    environment:
      - 'POSTGRES_DB=coaches'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0000'
    ports:
      - "5432:5433"

  app:
    build: /.
    container_name: 'java-app'
    ports:
      - "8080:8080"
    environment:
      - 'DB_URL=jdbc:jdbc:postgresql://postgres:5432/coaches'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=0000'
    depends_on:
      - postgres

#version: '3'
#services:
#  postgres:
#    image: 'postgres:latest'
#    container_name: 'coaches_postgres'
#    environment:
#      - 'POSTGRES_DB=coaches'
#      - 'POSTGRES_USER=postgres'
#      - 'POSTGRES_PASSWORD=0000'
#
#  app:
#    build: /.
#    container_name: 'java-app'
#    ports:
#      - "8080:8080"
#    environment:
#      - 'DB_URL=jdbc:jdbc:postgresql://localhost:5432/coaches'
#      - 'DB_USERNAME=postgres'
#      - 'DB_PASSWORD=0000'