version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'coaches_postgres'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB: coaches'
      - 'POSTGRES_USER: 3301'
      - 'POSTGRES_PASSWORD: 0000'

  app:
    build: /.
    container_name: 'java-app'

    ports:
    - "5432:5432"