server:
  port: 8030

logging:
  level:
    Coaches: debug
    liquibase: error
    hikari: debug
    root: error
    org.springframework: error
    org.apache.catalina: error


spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: db/changelog/master.xml
    enabled: true
